### ISSUE TITLE
Link the python-api somewhere

### ISSUE THREAD

**Issue by snwflake** [iTerm2/iTerm2#1]
I did some digging since [#3294](https://gitlab.com/gnachman/iterm2/issues/3294) and I was quite surprised that the API is already there :/

So after extracting the docs, and looking at [build.sh](https://github.com/gnachman/iTerm2/blob/master/api/library/python/iterm2/docs/build.sh) I figured... that path seems odd, let me just . . . 
[OH THERE WE GO!](https://iterm2.com/python-api/tutorial/index.html#tutorial-index)

There is no link anywhere suggestion the API already exists, so that would be great if you added that :)

Since I'm writing this already, where is the magic option `Select Scripts > New Python Script`?
I could redirect the question to GitLab if you wish.

**Comment by gnachman** [comment]
Install the nightly build and you'll find everything magically works. This feature isn't released yet which is why there's no link to it. Currently there is one link to the help which is from the built-in Python REPL. Please follow up on github if you have any questions.
